### ISSUE TITLE
Waterfox Current alongside Waterfox Classic

### ISSUE THREAD

**Issue by grahamperrin** [hawkeye116477/install-waterfox-linux#1]
Please, is there any _reasonably easy_ way to enhance the script?

As things are, if: 

1. `install_waterfox.sh` alongside `waterfox-56.2.14.en-US.linux-x86_64.tar.bz2` is followed by 
2. `install_waterfox.sh` alongside `waterfox-68.0b1.en-US.linux-x86_64.tar.bz2`

– then the installation of Waterfox Classic is overwritten by an installation of Waterfox Current (and without looking at the details of the overwrite, I might not trust the end result).

**Comment by hawkeye116477** [comment]
Yeah, problem is that Alex didn't changed appname in mozconfig, so folder is named waterfox and script overwrites it, just like installer on Windows. Anyway, we can make checking if tar is named `waterfox-68*`, then unpack it to temporary directory, rename folder and copy it to `~/Apps`.

**Comment by hawkeye116477** [comment]
@grahamperrin For now I added separate script for Waterfox Current. Check if it's working fine for you :smile:.

**Comment by grahamperrin** [comment]
Thanks, sorry I haven't found an opportunity to test …

**Comment by hawkeye116477** [comment]
@grahamperrin There is new script https://github.com/hawkeye116477/install-waterfox-linux/blob/master/install_waterfox.sh available now. It's one for all and it can also install AppImage packages.
