### ISSUE TITLE
"Profile launch mode" error in .desktop file

### ISSUE THREAD

**Issue by ordilibre** [hawkeye116477/install-waterfox-linux#4]
Hi,

In line 569, there is a double '-' instead of a single one :
`Exec=waterfox-$lowerChosenPackageType --ProfileManager`
should be
`Exec=waterfox-$lowerChosenPackageType -ProfileManager`

Thank you for the script

**Comment by hawkeye116477** [comment]
Well, Waterfox and Firefox command line help mentions that should be with double `-` and that works fine. Fedora also uses double sign.
However looks like that also works good with single `-`.

Update:
As I read:
> The convention is that '-' usually represents short single character options whereas '--' are long verbose options.

So double dash is quite more appropriate, but if you look at comments in code =>  https://github.com/MrAlex94/Waterfox/blob/classic/toolkit/xre/nsAppRunner.cpp#L501, they say that both forms are accepted.
